// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8nyuw_fCHIgDYaWgXg4fRGfdCq-GjzSo',
    appId: '1:646278214466:web:dfd4efe01747fd81ff0edb',
    messagingSenderId: '646278214466',
    projectId: 'instagram-clone-dbcea',
    authDomain: 'instagram-clone-dbcea.firebaseapp.com',
    storageBucket: 'instagram-clone-dbcea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJJBZ1FobJZES3unKpcWrwTwSEVaPE3EE',
    appId: '1:646278214466:android:462bbf4ff45fcb5aff0edb',
    messagingSenderId: '646278214466',
    projectId: 'instagram-clone-dbcea',
    storageBucket: 'instagram-clone-dbcea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr66FwgFQ8-isCYkluTEzezE24bTI7P-M',
    appId: '1:646278214466:ios:920d6e9f0b32eaa5ff0edb',
    messagingSenderId: '646278214466',
    projectId: 'instagram-clone-dbcea',
    storageBucket: 'instagram-clone-dbcea.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr66FwgFQ8-isCYkluTEzezE24bTI7P-M',
    appId: '1:646278214466:ios:4aa6e5e1478a88a0ff0edb',
    messagingSenderId: '646278214466',
    projectId: 'instagram-clone-dbcea',
    storageBucket: 'instagram-clone-dbcea.appspot.com',
    iosBundleId: 'com.example.instagram.RunnerTests',
  );
}